name: writer
favicon: null
layout_spectrum: 0.73609
typography_spectrum: 0.20001
title: 'Matt Bubbers: Freelance'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f5e2'
    - '#1d1814'
    - '#4d3c2c'
    - '#a08e50'
    - '#beb17d'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
